[package]
name = "nogame"
version = "0.1.0"
cairo-version = ">=2.0.0-rc0"
authors = ["ametel01"]
license = "MIT"

[dependencies]
starknet = ">=2.0.0-rc0"

[[target.starknet-contract]]

[scripts]
test = "cairo-test ."

[lib]
sierra = true  # Enable Sierra codegen.
casm = false   # Enable CASM codegen.